apiVersion: batch/v1
kind: CronJob
metadata:
  name: jackie-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: dockerhub-pull
          imagePullPolicy: IfNotPresent
          containers:
          - name: jackie-cronjob
            image: xiujungao/jackie-cronjob:master

          restartPolicy: OnFailure
      backoffLimit: 4
