apiVersion: batch/v1
kind: CronJob
metadata:
  name: jackie-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jackie-cronjob
            image: jackie-cronjob
            args:
            - /bin/sh
            - -c
            - curl -X POST http://jackie-cronjob:8080/actuator/shutdown
          restartPolicy: Never
      backoffLimit: 4
